# Generated by Django 6.1.1 on 2026-10-05 20:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='articles_ar_created_b5cc75_idx',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='تصویر مقاله'),
        ),
        migrations.AddField(
            model_name='article',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='هرچه عدد بالاتر باشد الویت نمایش مقاله بیشتر است', verbose_name='الویت نمایش'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['priority'], name='articles_ar_priorit_41de3a_idx'),
        ),
    ]
