# Generated by Django 6.1.1 on 2026-10-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_article_articles_ar_created_b5cc75_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-priority'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
    ]
