# Generated by Django 6.1.1 on 2026-09-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('speciality', models.CharField(max_length=100, verbose_name='تخصص')),
            ],
            options={
                'verbose_name': 'تیم',
                'verbose_name_plural': 'اعضای تیم',
            },
        ),
    ]
