# Generated by Django 6.1.1 on 2026-09-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_active',
            field=models.BooleanField(default=True, help_text='فعال یا غیر فعال', verbose_name='وضعیت عضو'),
        ),
    ]
