# Generated by Django 6.1.1 on 2026-10-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='team/profile_pictures'),
        ),
    ]
