# Generated by Django 6.1.1 on 2026-10-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='نشان دهنده الویت نمایش اعضای تیم عدد بالاتر یعنی الویت بیشتر', verbose_name='اولویت نمایش'),
        ),
        migrations.AlterField(
            model_name='team',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='team/profile_pictures', verbose_name='عکس پروفایل'),
        ),
    ]
