# Generated by Django 6.1.1 on 2026-10-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_team_priority_alter_team_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='نشان دهنده الویت نمایش اعضای تیم، عدد بالاتر یعنی الویت بیشتر', verbose_name='اولویت نمایش'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['priority'], name='team_team_priorit_f48c29_idx'),
        ),
    ]
