# Generated by Django 6.1.1 on 2026-09-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=100, verbose_name='تایتل اصلی')),
                ('short_description', models.TextField(max_length=500, verbose_name='توضیح کوتاه')),
                ('banner', models.ImageField(upload_to='home/banners', verbose_name='بنر سایت')),
                ('card1_title', models.CharField(max_length=100, verbose_name='تایتل کارت اول')),
                ('card1_description', models.TextField(max_length=500, verbose_name='توضیح کارت اول')),
                ('card2_title', models.CharField(max_length=100, verbose_name='تایتل کارت دوم')),
                ('card2_description', models.TextField(max_length=500, verbose_name='توضیح کارت دوم')),
                ('card3_title', models.CharField(max_length=100, verbose_name='تایتل کارت سوم')),
                ('card3_description', models.TextField(max_length=500, verbose_name='توضیح کارت سوم')),
                ('company_phone', models.CharField(max_length=11, verbose_name='شماره تلفن شرکت')),
                ('company_email', models.EmailField(max_length=100, verbose_name='ایمیل شرکت')),
            ],
            options={
                'verbose_name': 'صفحه اصلی',
                'verbose_name_plural': 'تنظیمات صفحه اصلی',
            },
        ),
    ]
