# Generated by Django 6.1.1 on 2026-10-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='site_is_active',
            field=models.BooleanField(default=True, verbose_name='فعالی/غیر فعالی سایت'),
        ),
    ]
