# Generated by Django 6.1.1 on 2026-10-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_site_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='footer_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات فوتر'),
        ),
    ]
