# Generated by Django 6.1.1 on 2026-10-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_home_footer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='footer_description',
            field=models.TextField(blank=True, default='رایمند شریف', null=True, verbose_name='توضیحات فوتر'),
        ),
    ]
