# Generated by Django 6.1.1 on 2026-10-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_home_footer_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField(verbose_name='اهداف شرکت')),
                ('pros1_title', models.CharField(max_length=100, verbose_name='ویژگی اول')),
                ('pros1_description', models.TextField(max_length=300, verbose_name='توضیح ویژگی اول')),
                ('pros2_title', models.CharField(max_length=100, verbose_name='ویژگی دوم')),
                ('pros2_description', models.TextField(max_length=300, verbose_name='توضیح ویژگی دوم')),
                ('pros3_title', models.CharField(max_length=100, verbose_name='ویژگی سوم')),
                ('pros3_description', models.TextField(max_length=300, verbose_name='توضیح ویژگی سوم')),
                ('pros4_title', models.CharField(max_length=100, verbose_name='ویژگی چهارم')),
                ('pros4_description', models.TextField(max_length=300, verbose_name='توضیح ویژگی چهارم')),
            ],
            options={
                'verbose_name': 'درباره ما',
            },
        ),
    ]
