# Generated by Django 6.1.1 on 2026-10-06 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_aboutus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'درباره ما', 'verbose_name_plural': 'درباره ما'},
        ),
    ]
