# Generated by Django 6.1.1 on 2026-10-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_aboutus_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.AddField(
            model_name='home',
            name='goal',
            field=models.TextField(blank=True, null=True, verbose_name='اهداف شرکت'),
        ),
    ]
