# Generated by Django 6.1.1 on 2026-10-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_aboutus_home_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='تایتل ویژگی')),
                ('description', models.TextField(max_length=150, verbose_name='توضیح ویژگی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعلی/غیر فعالی')),
                ('priority', models.IntegerField(default=0, verbose_name='الویت نمایش')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی ها',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='TimeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
