# Generated by Django 6.1.1 on 2026-10-08 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_feature_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='bridge_text',
            field=models.CharField(default='', help_text='متنی که بین دو بخش مختلف تایم لاین روی خط نمایش داده میشود', max_length=100, verbose_name='توضیح پل'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='description',
            field=models.CharField(default='', max_length=100, verbose_name='توضیح تایم لاین'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='تایتل تایم لاین'),
        ),
        migrations.AddField(
            model_name='timeline',
            name='year',
            field=models.PositiveIntegerField(default=1900, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='سال تایم لاین'),
        ),
    ]
