# Generated by Django 6.1.1 on 2026-10-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_timeline_bridge_text_timeline_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeline',
            options={'ordering': ['-year'], 'verbose_name': 'خط زمانی', 'verbose_name_plural': 'خط های زمانی'},
        ),
        migrations.AddField(
            model_name='timeline',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعالی/غیر فعالی'),
        ),
    ]
