# Generated by Django 6.1.1 on 2026-10-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_timeline_options_timeline_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='bridge_text',
            field=models.CharField(blank=True, help_text='متنی که بین دو بخش مختلف تایم لاین روی خط نمایش داده میشود', max_length=100, null=True, verbose_name='توضیح پل'),
        ),
    ]
