# Generated by Django 6.1.1 on 2026-10-08 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_timeline_bridge_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='year',
            field=models.PositiveIntegerField(default=1900, unique=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(9999)], verbose_name='سال تایم لاین'),
        ),
    ]
