# Generated by Django 6.1.1 on 2026-10-08 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_timeline_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeline',
            options={'ordering': ['year'], 'verbose_name': 'خط زمانی', 'verbose_name_plural': 'خط های زمانی'},
        ),
    ]
