# Generated by Django 6.1.1 on 2026-10-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_timeline_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['priority'], name='home_featur_priorit_e911de_idx'),
        ),
        migrations.AddIndex(
            model_name='timeline',
            index=models.Index(fields=['year'], name='home_timeli_year_7fc0e1_idx'),
        ),
    ]
